###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@host = localhost:8443

### Suche alle Buecher
https://{{host}}/buecher

### Suche mit vorhandener Buch-ID
https://{{host}}/buecher/00000000-0000-0000-0000-000000000001

### Suche mit vorhandener Buch-ID und Versionsnummer
https://{{host}}/buecher/00000000-0000-0000-0000-000000000001
If-None-Match: "0"

### Suche mit vorhandener Buch-ID und falscher Versionsnummer
https://{{host}}/buecher/00000000-0000-0000-0000-000000000001
If-None-Match: 0

### Suche mit ungueltiger Buch-ID
https://{{host}}/buecher/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

### Suche mit nicht-vorhandener Buch-ID
https://{{host}}/buecher/99999999-9999-9999-9999-999999999999

### Suche mit vorhandenem Titel
https://{{host}}/buecher?titel=a

### Suche mit vorhandener ISBN
https://{{host}}/buecher?isbn=978-3897225831

### Suche mit vorhandenen Schlagwoertern
https://{{host}}/buecher?javascript=true&typescript=true

### Suche mit vorhandenem Schlagwort "JAVASCRIPT"
https://{{host}}/buecher?javascript=true

### Suche mit vorhandenem Schlagwort "TYPESCRIPT"
https://{{host}}/buecher?&typescript=true

### Suche mit gueltiger Buchart
https://{{host}}/buecher?art=KINDLE

### Suche mit gueltigem Rating
https://{{host}}/buecher?rating=1

### Suche lieferbare Buecher
https://{{host}}/buecher?lieferbar=true

### Optionen zu Buch-ID
OPTIONS https://{{host}}/buecher/00000000-0000-0000-0000-000000000001
