###
### N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
###

@host = localhost:8443

### Suche Vorname, Nachname und KundenKundenart von allen Kundenn
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  kunden {
    vorname
    nachname
    kundenart
  }
}

### Suche Vorname, Nachname, KundenKundenart und PLZ von einem Kunde mit vorhandener Kunde-ID
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  kunde(id: "00000000-0000-0000-0000-000000000001") {
    vorname
    nachname
    kundenart
    plz
  }
}

### Suche Vorname und Kundenart von Kundenn mit vorhandenem Titel
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  kunden(vorname: "Fabian") {
    vorname
    kundenart
  }
}

### Neuer Kunde anlegen
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  createKunde(
  vorname: "Neuer",
  nachname: "Kunde",
  kundenart: "Privatkunde",
  geschlecht: "M",
  hausnummer: 99,
  plz: 73849,
  aktiv: true,
  registrierungsdatum: "2019-02-01T00:00:00.000Z",
  strasse: "Neue Strasse",
  zusatzinfo: "New Buyer",
  ) {
    _id
  }
}

### Vorhandener Kunde aktualisieren
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  updateKunde(
  _id: "00000000-0000-0000-0000-000000000003",
  vorname: "Testtesttest",
  nachname: "Aendern",
  kundenart: "Gewerbekunde",
  geschlecht: "W",
  hausnummer: 184,
  plz: 23456,
  aktiv: false,
  registrierungsdatum: "2019-01-01T00:00:00.000Z",
  strasse: "Anderestrasse",
  zusatzinfo: "Old Buyer",
  bestellungen: "Veraendertes Verhalten",
    version: 0
  ) {
    version
  }
}

### Vorhandener Kunde loeschen
POST https://localhost:8443/api
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  deleteKunde(id: "00000000-0000-0000-0000-000000000004")
}
